development:
  adapter: sqlite3
  database: db/app.sqlite3.db

production:
  host: ec2-54-221-255-192.compute-1.amazonaws.com
  adapter: postgresql
  database: d72fe54392av9j
  username: ggcennoctzrruk
  password: ueFg4ZVGq-Y9lPQMb0QRlmoSZL
  port: 5432
  psql: heroku pg:psql --app ruby-messager DATABASE