development:
  adapter: sqlite3
  database: db/app.sqlite3.db

production:
  host: ec2-54-163-226-30.compute-1.amazonaws.com
  adapter: postgresql
  database: dba94lijtqhs5i
  username: zdhtxdbchjpydu
  password: oqvQ371eBR2KrLIck8xLDmlJEu
  port: 5432
  psql: heroku pg:psql --app ruby-messager DATABASE
  url: postgres://zdhtxdbchjpydu:oqvQ371eBR2KrLIck8xLDmlJEu@ec2-54-163-226-30.compute-1.amazonaws.com:5432/dba94lijtqhs5i